server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # This ensures that any URL that isn't a direct file match falls back to index.html
    # This is required for React Router / Single Page Applications (SPAs)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Properly serve the mounted product images
    location /products/ {
        alias /usr/share/nginx/html/products/;
    }
}
