import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Handles the generative virtual try-on for Peer Jewelry.
 * Uses Gemini 2.5 Flash Image to fuse product images with user photos.
 */
export const generateJewelryTryOn = async (apiKey, userPhotoBase64, productPhotoBase64, category = 'rings', productName = 'jewelry') => {
    const genAI = new GoogleGenerativeAI(apiKey);

    // Using the supported Gemini 2.5 Flash Image ID to avoid 404 errors
    const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash-image"
    });

    const bodyPartMap = {
        rings: 'hand/finger',
        necklaces: 'neck/chest area',
        earrings: 'ears',
        bracelets: 'wrist'
    }
    const bodyPart = bodyPartMap[category] || 'appropriate body part'
    const itemName = category === 'rings' ? 'ring'
        : category === 'necklaces' ? 'necklace'
            : category === 'earrings' ? 'earring'
                : category === 'bracelets' ? 'bracelet'
                    : 'jewelry'

    let placementInstruction = '';
    if (category === 'rings') {
        placementInstruction = `
    1. Identify the ring finger on the hand in Input 1.
    2. Place the ring from Input 2 realistically onto the base of that finger.
    3. Ensure the ring band wraps behind the finger (occlusion) for a natural fit.`;
    } else if (category === 'bracelets') {
        placementInstruction = `
    1. Identify the wrist in Input 1.
    2. Place the bracelet from Input 2 realistically around the wrist.
    3. Ensure the bracelet wraps behind the wrist (occlusion) for a natural fit.`;
    } else if (category === 'necklaces') {
        placementInstruction = `
    1. Identify the neck/chest area in Input 1.
    2. Place the necklace from Input 2 realistically around the neck, resting on the chest.
    3. Ensure the necklace chain wraps behind the neck (occlusion) for a natural fit.`;
    } else if (category === 'earrings') {
        placementInstruction = `
    1. Identify the ears in Input 1.
    2. Place the earrings from Input 2 realistically hanging from the earlobes.`;
    } else {
        placementInstruction = `
    1. Identify the appropriate body part (${bodyPart}) in Input 1.
    2. Place the ${itemName} from Input 2 realistically onto the ${bodyPart}.`;
    }

    const prompt = `
    TASK: Realistic Virtual Jewelry Try-On.
    INPUT 1: A photo of a user's ${bodyPart}.
    INPUT 2: A product image of a luxury ${itemName} from Peer Jewelry (${productName}).
    
    INSTRUCTION:${placementInstruction}
    4. Match the lighting, reflections, and shadows of the ${itemName} to the skin tone and ambient light of the user's photo.
    5. Output ONLY the final merged photorealistic image.
  `;

    try {
        const result = await model.generateContent({
            contents: [
                {
                    role: "user",
                    parts: [
                        { text: prompt },
                        { inlineData: { data: userPhotoBase64, mimeType: "image/jpeg" } },
                        { inlineData: { data: productPhotoBase64, mimeType: "image/jpeg" } },
                    ],
                },
            ],
            // This config is critical to receive an image back instead of text
            generationConfig: {
                responseModalities: ["IMAGE"],
            },
        });

        const response = await result.response;
        const candidates = response.candidates;

        // Extract the generated image data from the response parts
        const generatedPart = candidates[0].content.parts.find(part => part.inlineData);

        if (generatedPart) {
            return `data:image/png;base64,${generatedPart.inlineData.data}`;
        } else {
            throw new Error("No image was generated by the model.");
        }
    } catch (error) {
        console.error("Try-On Error:", error);
        throw error;
    }
};
